apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-api
  namespace: default
  labels:
    app: journal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal-api
  template:
    metadata:
      labels:
        app: journal-api
    spec:
      serviceAccountName: journal-api-sa
      nodeSelector:
        karpenter.sh/nodepool: default
      containers:
      - name: journal-api
        image: 324547056370.dkr.ecr.us-east-1.amazonaws.com/journal-api:v56
        ports:
        - containerPort: 8000
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: ALLOWED_ORIGINS
          value: "https://www.aws11.shop,https://aws11.shop,https://api.aws11.shop"
        - name: DEBUG
          value: "False"
        - name: ENVIRONMENT
          value: "production"
        - name: S3_BUCKET_NAME
          value: "knowledge-base-test-6575574"
        - name: AGENT_API_URL
          value: "http://agent-api-service:8000"
        livenessProbe:
          httpGet:
            path: /journal/health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /journal/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "216Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: journal-api-service
  namespace: default
spec:
  selector:
    app: journal-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: journal-api-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::324547056370:role/journal-api-secrets-role